#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You cannot commit directly to the main branch. Please create a separate branch to work within."
  exit 1
fi

